const employerSchema = new mongoose.Schema({
    employerID:{
        type: Number,
        autogenerated: true
    },
    employerName:{
        type: String,
        required: true,
    },
    companyName: {
        type: String,
        required: true,
    },
    email:{
        type: String,
        required: true,
        unique: true,
    },
    password:{
        type: String,
        required: true,
        minlength: 8
    },
    location: {
        country: {
            type: String,
            required: true
        },
        city:{
            type: String,
            required: true
        },
        poBox:{
            type: Number,
            required: true
        }
    },
    contactNumber:{
        type:Number,
        required:true
    },
    verified: {
        type: Boolean,
        default: false
    },
    sharesList: {
        degree: 
        {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Degree',
            required: true
        }
    }

});